### ISSUE TITLE
Remove Dep

### ISSUE THREAD

**Issue by mahmoudhossam** [Alikhll/golang-developer-roadmap#10]
While Dep was the official experiment, developers new to Go are encouraged to use [Go modules](https://github.com/golang/go/wiki/Modules) instead since they are part of the official toolchain now.

I think it's time we stop recommending Dep to new developers and stick with the official standard.

**Comment by Alikhll** [comment]
@mahmoudhossam Yeah I see, that sounds fine, could you please remove dep from the chart and make PR?

**Comment by Inconnu08** [comment]
@Alikhll I can remove dep from the chart right now.

**Comment by Alikhll** [comment]
@Inconnu08 It's my pleasure, but please don't forget compress the output image.
Cheers
