### ISSUE TITLE
客户端侧负载均衡组件

### ISSUE THREAD

**Issue by chenkline** [Alikhll/golang-developer-roadmap#11]
感觉缺少客户端侧负载均衡组件(独立于微服务框架的负载均衡)，类似java的Ribbon这样的组件

**Comment by Alikhll** [comment]
@chenkline  Could you please write your issue in English to make understandable for everyone?

**Comment by Quorafind** [comment]
@Alikhll What he said means that there has no load balancer director/component for client ( different from /independent of load balancer in micro-service framework  ) such as [ribbon](https://github.com/Netflix/ribbon) in java. Hope this will help you share your idea with him. If you can answer this, you can @me and I will translate it to reply him.

**Comment by Alikhll** [comment]
@Quorafind  Actually about loadbalancing there are lots of ways and strategies to do that and I didn't want to encourage new Go developers to choose specific one is in my mind only! gRPC, other frameworks and also orchestration tools such as k8s support that(DNS loadbalancer, etc), so I think it does not suitable way for this chart to direct developers who are new in these technologies to a way I like that...
there are lots of other things are not include in this chart, I just though about the most important things any developer should care about that though.

**Comment by Quorafind** [comment]
@chenkline 实际上负载均衡有很多方案和很多策略来实现，但是我不推荐 Go 的初学者在我的想法中选择特定的一个（译注：这里应该是指不需要提及）。gRPC 或者其它框架还有 orchestration 工具例如 k8s 都会支持负载均衡（DNS 负载均衡之类的），所以我不认为这个图表应该指导开发者，尤其是那些初来乍到的开发者来研究这些技术。。。
这个图表有太多内容没有被囊括进去了，我只是把我认为的初学者最需要了解的东西放了进去。

@Alikhll Done ; )

**Comment by Alikhll** [comment]
@Quorafind Great, Thank you ;))
