### ISSUE TITLE
Rename MySql to MySQL

### ISSUE THREAD

**Issue by ziyaddin** [Alikhll/golang-developer-roadmap#20]
![image](https://user-images.githubusercontent.com/1016523/57107593-72553780-6d41-11e9-839b-a31c113d3d1e.png)

**Comment by Alikhll** [comment]
@ziyaddin please fix that and make PR

**Comment by zobninatn** [comment]
fix added in the #23 PR

**Comment by ziyaddin** [comment]
Thanks @zobninatn
