### ISSUE TITLE
Add some awesome projects

### ISSUE THREAD

**Issue by Quorafind** [Alikhll/golang-developer-roadmap#25]
For example, [Staffjoy](https://github.com/Staffjoy/v2) is an awesome project based on golang.
Maybe we can add it to a node ‘Project’

Just like this:

16. Project
- [Staffjoy](https://github.com/Staffjoy/v2)

What do you think of it?

**Comment by Alikhll** [comment]
Yeah, it seems nice
please add this to the roadmap and make PR!
Cheers ;)

**Comment by Quorafind** [comment]
OK, I will do this on the weekend.
