### ISSUE TITLE
Recommend to add

### ISSUE THREAD

**Issue by micshome** [Alikhll/golang-developer-roadmap#39]
Hi, really like this project :)
Recommend to several projects we years already use in prod:
1. Config management:  [viper](https://github.com/spf13/viper )
2. WebServer - simple and very fast, on fasthttp base: [atreugo](https://github.com/savsgio/atreugo)
3. Distributed cache: [aerospike](https://www.aerospike.com/)
4. Log management system: [graylog](https://www.graylog.org/products/open-source)
5. Task scheduling: [cron](https://godoc.org/github.com/robfig/cron)

Thank you!

**Comment by Alikhll** [comment]
Hi @micshome , I am checking them out, early future I'll be informing you for PR creation if I can find a place for them although

**Comment by Alikhll** [comment]
however, all the tools you have introduced are great, but actually I don't see any point to make the roadmap more complicated, thanks for the issue was submitted by you :)
