### ISSUE TITLE
Add Fiber into framework list

### ISSUE THREAD

**Issue by maplerichie** [Alikhll/golang-developer-roadmap#43]
Fiber is a great framework, simple, good documentation, good team, blazing fast (tested in local environment, production havent yet)

https://github.com/gofiber/fiber

**Comment by Alikhll** [comment]
@maplerichie seems interesting,
create PR
I'll have a look at that immediately

**Comment by Fenny** [comment]
👋 _https://github.com/Alikhll/golang-developer-roadmap/pull/44_
