### ISSUE TITLE
Possibly some more helpful pointers to the roadmap

### ISSUE THREAD

**Issue by sks** [Alikhll/golang-developer-roadmap#5]
Not sure how to contribute or if the topics are already covered.

Noting them down in case some one is interested.

* [Web : Gorilla toolkit](http://www.gorillatoolkit.org/)
* [DB: bolt DB](https://github.com/etcd-io/bbolt)
* [DB Migration](https://github.com/golang-migrate/migrate)
* [CLI tools: Cobra](https://github.com/spf13/cobra)
* [CLI Tools: cli](https://github.com/urfave/cli)
* [Cache: LRU Map](https://github.com/hashicorp/golang-lru)
* [Mocking: counterfeiter](https://github.com/maxbrunsfeld/counterfeiter)
* [Monitoring: prometheus](https://github.com/prometheus/client_golang)

**Comment by Alikhll** [comment]
Thanks for that, after a bit research on some tools you have suggested, I will let you know to add them to the chart please.
follow this issue please and we can discus more about details and how you can contribute.

**Comment by Alikhll** [comment]
@sks 
hi, actually I read about all of libraries you have written, in fact the roadmap should not contains all of libraries in communities, but we are focusing on some specif part which is important for every developers who want to make progress so we should ignore lots of packages, somehow the cli part is missing in the roadmap though, could you please add CLI part and then add "Cobra" and "urfave/cli" to the roadmap due this issue? and make pull request please

**Comment by Alikhll** [comment]
Thanks for PR @sks
