### ISSUE TITLE
Roadmap not readable if using GitHub in Dark Mode

### ISSUE THREAD

**Issue by OscarVanL** [Alikhll/golang-developer-roadmap#69]
Either the image shouldn't have a transparent background, or the text should all be in boxes/bubbles.

This is how it looks:
![image](https://user-images.githubusercontent.com/7999692/114902457-c31aa980-9e0d-11eb-8228-dd795ba928dd.png)

**Comment by petrvelicka** [comment]
Can confirm even when using the gray version
![image](https://user-images.githubusercontent.com/66218106/114913643-ba33d300-9e21-11eb-8dcb-b8471cdd0484.png)

**Comment by Alikhll** [comment]
oh yeah, i was wondering if you could have made that fixed?
