### ISSUE TITLE
Translation For This Roadmap 

### ISSUE THREAD

**Issue by Quorafind** [Alikhll/golang-developer-roadmap#8]
I did't improve this roadmap, but I translated it into Chinese. [Here](https://github.com/Quorafind/golang-developer-roadmap-cn)
Hope this will help more people.

**Comment by Alikhll** [comment]
@Quorafind That's great, could you please add your translated page to the original repo, then create a link to navigate between Chinese and English version, make PR please!

**Comment by Quorafind** [comment]
@Alikhll Sure, I will do it tonight. Maybe five hours later.

**Comment by Alikhll** [comment]
Great ;)

**Comment by Quorafind** [comment]
@Alikhll Someone from Chinese social media love this chart, my repository had also gain over 200 stars. Your work is really appreciated.

**Comment by Alikhll** [comment]
Awesome, It's my pleasure to hear that.

**Comment by Quorafind** [comment]
@Alikhll Done. I add a link in the main markdown file and a link in my translated markdown file.

**Comment by Alikhll** [comment]
@Quorafind Cheers ;)
